### ISSUE TITLE
Disable-Module-Fetch: true header support

### ISSUE THREAD

**Issue by futurist** [goproxy/goproxy#39]
In the document https://proxy.golang.org/github.com/, there is a `Disable-Module-Fetch: true` and index service to be used to mirror a proxy, can this lib support this header?

**Comment by aofei** [comment]
Usually I would advise people to implement "unwritten" features like `Disable-Module-Fetch` themselves, and that's pretty easy if you're using Goproxy as a lib. But since Goproxy [introduced support for a simple cli](https://github.com/goproxy/goproxy/commit/cdc4fb1e9d06915554ee2ce2d4e48f8c8e9e8260), it might make sense to add support for `Disable-Module-Fetch` now. I'll take a look at this.

But to be clear, something like [index.golang.org](https://index.golang.org) will not be added, it should be implemented by the upper layer. Introducing a database is something we don't want, it would complicate the project.
